### ISSUE TITLE
The ”Dynamic Plugin Loading“ does not work in docker

### ISSUE THREAD

**Issue by crazypenguin** [mozilla-services/hindsight#100]
when i use https://github.com/Securing-DevOps/logging-pipeline to test hindsight，i met below：

through https://github.com/mozilla-services/hindsight/blob/master/docs/architecture.md，the ”Dynamic Plugin Loading“ is work with plugin stop、restart...

but when i run（i have mounted the ’load‘ directory using ‘-v $(pwd)/load:/app/load’）：
#( 04/06/17@10:31上午 )( wbhuang@kali ):~/Downloads/logging-pipeline@master✗✗✗
touch load/input/input_nginx.cfg

and then the docker container mozilla/hindsight output like this：

#( 04/06/17@ 9:58上午 )( wbhuang@kali ):~/Downloads/logging-pipeline@master✗✗✗
docker run -it \
-v $(pwd)/cfg:/app/cfg 
-v $(pwd)/logs:/app/logs 
-v $(pwd)/run:/app/run 
-v $(pwd)/output:/app/output -v $(pwd)/load:/app/load 
mozilla/hindsight
1491444261228820607 [info] hindsight starting
1491444261235703092 [info] input.input_nginx starting
1491444261236929714 [info] analysis.counter adding to thread: 0
1491444261238109989 [info] analysis.suspicious_threshold adding to thread: 0
1491444261238840247 [info] analysis.suspicious_signatures adding to thread: 0
1491444261239797534 [info] analysis.moving_average adding to thread: 0
1491444261240443598 [info] analysis.xss adding to thread: 0
1491444261240544755 [info] analysis_plugins starting thread: 0
1491444261241649250 [info] output.heka_debug starting
1491444261251112655 [info] output.heka_inject_payload starting
1491444262866958989 [info] input.input_nginx detaching received: 0 msg: 97235
1491445973525830672 [error] config_parser failed to move: load/input/input_nginx.cfg to run/input/input_nginx.cfg errno: 18

also for other cfg file is the same errno；
please help me to fix it！

**Comment by trink** [comment]
Support questions are better directed to the mailing list: https://mail.mozilla.org/listinfo/hindsight
Thanks

@mreid-moz should be able to provide some Docker setup advice when he returns from vacation next week
