### ISSUE TITLE
build hindsight on centos 6.8 while can't install parquet-cpp-0.0.1-Linux.rpm

### ISSUE THREAD

**Issue by crazypenguin** [mozilla-services/hindsight#101]
i have build hindsight on centos lastest，but my most hosts are centos6.8，so i copy all the builded rpm files to centos6.8. but they depend on GLIBC_2.14 and so on which is higher than centos6.8’s glibc2.12.

so i try to build on centos6.8,but i find:
[wbhuang@edu app]$ sudo rpm -ivh parquet-cpp-0.0.1-Linux.rpm                                 
error: Failed dependencies:                                                                  
        libc.so.6(GLIBC_2.14)(64bit) is needed by parquet-cpp-0.0.1-1.x86_64                 
        libstdc++.so.6(CXXABI_1.3.5)(64bit) is needed by parquet-cpp-0.0.1-1.x86_64          
        libstdc++.so.6(GLIBCXX_3.4.15)(64bit) is needed by parquet-cpp-0.0.1-1.x86_64        
        libstdc++.so.6(GLIBCXX_3.4.18)(64bit) is needed by parquet-cpp-0.0.1-1.x86_64   

so can you help me?

**Comment by trink** [comment]
Support questions are better directed to the mailing list: https://mail.mozilla.org/listinfo/hindsight
Thanks

This package is not maintained by Mozilla. The easiest thing would be to rebuild it for your target platform.  Submitting our local build/packaging changes to the parquet-cpp project is on my todo list but has been low priority.
