### ISSUE TITLE
[Feature request] option to make new output start reading at the end of the queues

### ISSUE THREAD

**Issue by champtar** [mozilla-services/hindsight#105]
To get better output performance, i'm switching from 1 ES output to 2
(stop hindsight, create 2 ES output with Uuid < '\x128' ...)
When starting hindsight again the 2 new outputs read hindsight queues from the beginning, thus sending duplicates logs to ES

Maybe we need a "read_queue_from=<beginning|end>" option ?

For now I plan to stop the input, wait until everything is sent, stop hindsight, remove the queues files, configure the new outputs, and start hindsight again.

**Comment by trink** [comment]
https://github.com/mozilla-services/hindsight/pull/30

**Comment by champtar** [comment]
thanks!
