### ISSUE TITLE
can't auto load the files which are new in the sandbox_load_path

### ISSUE THREAD

**Issue by crazypenguin** [mozilla-services/hindsight#114]
output logs like these:
1497866144474621657 [error] analysis_plugins failed to move: load/analysis/counter.lua to run/analysis/counter.lua errno: 18
1497866230594181684 [error] config_parser failed to move: load/analysis/counter.cfg to run/analysis/counter.cfg errno: 18

**Comment by trink** [comment]
The load and run directories must be on the same file system (rename is failing with errno 18 (Cross-device link))

**Comment by crazypenguin** [comment]
so,how can it run the right way using docker while passing '-v $(pwd)/load:/app/load' ?

**Comment by trink** [comment]
@crazypenguin There are some users running a docker setup that could probably help you; this question would get better visibility on the mailing list https://mail.mozilla.org/listinfo/hindsight
