### ISSUE TITLE
Improve the error message on *.rtc write errors

### ISSUE THREAD

**Issue by trink** [mozilla-services/hindsight#118]
input_plugins input.input_nginx hs_output_runtime_cfg failed

**Comment by jvehent** [comment]
I ran into this while testing the docker container and it wasn't obvious at first that hindsight wanted write access to the `run` directory. May I suggest something along the lines of `failed to write run/<full path>` ?

**Comment by trink** [comment]
See: https://github.com/mozilla-services/hindsight/issues/128

**Comment by trink** [comment]
8ae8f8ac3fad6c28e1f8bc1df05adb82dd4fd42b
