### ISSUE TITLE
test_config error when install hindsight

### ISSUE THREAD

**Issue by chwma** [mozilla-services/hindsight#119]
RT,  exec cmd
cd /root/hindsight
./build/run.sh build

part of error like this:

+ ctest -V
UpdateCTestConfiguration  from :/root/hindsight/release/DartConfiguration.tcl
Parse Config file:/root/hindsight/release/DartConfiguration.tcl
UpdateCTestConfiguration  from :/root/hindsight/release/DartConfiguration.tcl
Parse Config file:/root/hindsight/release/DartConfiguration.tcl
Test project /root/hindsight/release
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: test_config

1: Test command: /root/hindsight/release/src/test/test_config
1: Test timeout computed to be: 1500
1: /root/hindsight/release/src/test/test_config: symbol lookup error: /lib64/libluasandboxheka.so.0: undefined symbol: LSB_ERR_TERMINATED
1/1 Test #1: test_config ......................***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
	  1 - test_config (Failed)
Errors while running CTest

**Comment by trink** [comment]
When building locally please follow the instructions in the readme. The script above if for integration with TravisCI
