### ISSUE TITLE
hindsight appears to lose a single message when recovering from failure

### ISSUE THREAD

**Issue by joell** [mozilla-services/hindsight#120]
Consider the following hindsight input and output (with a default configuration):
```lua
-- input/tail.cfg
filename              = "tail.lua"
instruction_limit     = 0
ticker_interval       = 1
shutdown_on_terminate = true

input_filename        = "/tmp/hindsight-in.txt"

default_headers       = {
  Type = "TEST"
}

-- output/forward.cfg
filename              = "heka_tcp.lua"
instruction_limit     = 0
shutdown_on_terminate = true
message_matcher       = "TRUE"

address               = "127.0.0.1"
port                  = 4242
timeout               = 1
```

Now consider the following sequence of commands:
```sh
### On terminal one ###

$ hindsight defaults.cfg 7

### On terminal two ###

# start TCP receiver that spits frames to stdout
$ socat TCP-L:4242,fork - &  socat_pid=$!
# send a test event and watch it appear on stdout
$ echo TEST1 >> /tmp/hindsight-in.txt

# kill the TCP receiver and send a second test event
$ kill $socat_pid
$ echo TEST2 >> /tmp/hindsight-in.txt

# bring the TCP receiver back up
$ socat TCP-L:4242,fork - &
# (the second test event never appears)

# send a third test event and watch it appear on stdout
$ echo TEST3 >> /tmp/hindsight-in.txt
# (hindsight generates a "retry message <N> err: closed" error)
```

The expected result would be that when the `TEST2` event is sent while the TCP receiver is down that Hindsight would fail to deliver it, retry, and eventually deliver it when the TCP receiver comes back up.  Looking at the luasandbox-extensions code for `heka_tcp.lua` I don't see any edge case where the TCP send failure wouldn't result in a proper `-3` (retry) error code.  Yet, though the `heka_tcp` output does re-establish the connection once the receiver is brought back up, and the `TEST3` event makes it across, the `TEST2` event disappears into the ether.

(I used Hindsight 0.14.2, luasandbox 1.2.5, and luasandbox-extensions 2017.06.11 in testing this issue.)

**Comment by joell** [comment]
Update: I think this may be a flaw in the luasandbox extensions `output/heka_tcp.lua` module instead of in hindsight itself.

I notice that after the first `socat` process is killed, an `ss -tpn` reveals the TCP connection in a half-torn-down state, e.g.:
```
FIN-WAIT-2 0      0      127.0.0.1:4242               127.0.0.1:48122
CLOSE-WAIT 1      0      127.0.0.1:48122              127.0.0.1:4242
```

It appears that as long as `heka_tcp.lua`'s connection is in the `CLOSE-WAIT` state, that the `client:send` call will succeed one more time.  Then the connection will be fully torn down.  After that subsequent `send`'s yield errors, and `heka_tcp.lua` returns -3 (retry), which hindsight processes correctly.

**Comment by trink** [comment]
Sorry for the delay I was on PTO.  This is known behavior (send returning success on the client (when the message is queued) even though the server never receives it).  I was unable to find the discussion thread but it would have been around the time of https://github.com/mozilla-services/lua_sandbox_extensions/pull/66.  We primarily use this output for testing and experimentation so it was deemed 'good enough' however the issue can be addressed in several ways the easiest being altering the way that plugin handles checkpointing.

**Comment by joell** [comment]
Alright.  I've closed the issue as it's in the LSB extensions and not Hindsight itself.

My use case was one of looking for reliable network forwarding with a disk-based queue in the event of outages.  The only way I could think of reliably fixing the issue in the TCP plugin would be to have the recipient send some kind of application-level ACK; without that, the sender would never know if the packet had been received by the recipient Hindsight process or just by the kernel buffers on that system.  Ideally, I wouldn't want the sending process to return a success status code until and unless the recipient has successfully called and returned from `inject_message` (strongly implying the message has been serialized to disk on the recipient system).  To that end...

  1. Would you be open to a pull request on the [mozilla-services/lua_sandbox_extensions](https://github.com/mozilla-services/lua_sandbox_extensions) repo if I found the time to implement an ACK-based approach (either as a modification to heka_tcp or as a separate plugin)?
  2. Do you have any recommendations about how that might be done most efficiently while fully taking advantage of Hindsight's checkpointing system?

Thanks for all the hard work you've put into making this framework!

**Comment by trink** [comment]
1) The ACK approach would definitely be a different plugin as it would change the protocol and throughput characteristics.

2) We could switch to an async checkpoint and always have the output be one message behind (i.e. update the checkpoint to the previous message when the current message is successfully queued).  Under normal working conditions this will duplicate the last message anytime the plugin is restarted (shutdown could be special cased to avoid this but it may be a little ugly (i.e. sending an extra message))

**Comment by bbinet** [comment]
@joell I'm also facing the same issue: were you able to implement the ACK-based approach you've described?

**Comment by bbinet** [comment]
Also sometimes, I loose a few messages (not a single one): do you think this can be the same issue or a different one?

Typically, I can reproduce the loss of message(s) when I restart the hindsight process that runs the heka_tcp input plugin.

**Comment by trink** [comment]
@bbinet depending on how the network failure(s) unfold I wouldn't rule it out; typically it will drop one message for every dropped connection.  Even if you had a reproducible case that dropped say two messages the solution would be the same... a new protocol.

**Comment by bbinet** [comment]
@trink Do you think a new protocol with acknowledgments would be a lot of work?

I was also wondering if I should rather implement new MQTT input/output sandboxes to replace heka_tcp sandboxes for my use case, but I need to find a good MQTT lua lib: do you know any good lua lib for MQTT?
I've came accross https://github.com/Yongke/luamqttc but I haven't played with it yet and it seems to require a patched version of luasec.

**Comment by trink** [comment]
A synchronous or  asynchronous version would be a relatively small change in terms of LOC.  You will spend more time testing, profiling, and tuning.

**Comment by bbinet** [comment]
I see, thanks for your answer.
I think I'm going to explore the MQTT road as Kafka seem too heavyweight for our own use case (the volume of data we transport is not that high) and would too complicated for us to deploy.

**Comment by trink** [comment]
Personally I would wrapper an existing C lib:
https://www.wolfssl.com/products/wolfmqtt/
https://www.eclipse.org/paho/clients/c/embedded/

**Comment by bbinet** [comment]
Actually, https://github.com/Yongke/luamqttc is a lua wrapper for the [MQTT paho C lib (your 2nd link) ](https://www.eclipse.org/paho/clients/c/embedded/)
