### ISSUE TITLE
docker build fails with "Could not find a package configuration file provided by "aws-cpp-sdk-core""

### ISSUE THREAD

**Issue by g-k** [mozilla-services/hindsight#130]
Running `docker build .` fails on the https://github.com/mozilla-services/lua_sandbox_extensions/ build step with:

```
CMake Error at aws/CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "aws-cpp-sdk-core"
  (requested version 1.1.46) with any of the following names:

    aws-cpp-sdk-coreConfig.cmake
    aws-cpp-sdk-core-config.cmake

  Add the installation prefix of "aws-cpp-sdk-core" to CMAKE_PREFIX_PATH or
  set "aws-cpp-sdk-core_DIR" to a directory containing one of the above
  files.  If "aws-cpp-sdk-core" provides a separate development package or
  SDK, be sure it has been installed.
```

Adding `–DEXT_aws=false` to https://github.com/mozilla-services/hindsight/blob/b8c99ccac1dd6b61dd7ea67202c4b358e6040ce2/Dockerfile#L43 failed with the same error too.

I'm curious whether other people are see this error on a clean checkout too.

**Comment by trink** [comment]
Yeah that list should be inverted and specify what is wanted.  Instead it picks up new stuff that in many cases will break the build because of dependency issues.

**Comment by trink** [comment]
b1aba233e99239f9d311a12b415764f2b221ab34
