### ISSUE TITLE
Allow to require io/os module in hindsight config file

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/hindsight#151]
It would be very helpful to have full lua access in the hindsight config file.
For example this would allow us to require os/io/cjson modules to read config from environment variables or parse external json files to get hindsight config.

@trink Does it sound reasonable to you?

**Comment by trink** [comment]
In general we use a generator when we need functionality like that (e.g. puppet).  The cfg should remain just a declarative cfg; with the new decoder stuff it is already becoming a bit more complicated than I would like.

**Comment by bbinet** [comment]
Ok, let's close this issue.
