### ISSUE TITLE
Remove CircleCI jobs and clean up Travis jobs

### ISSUE THREAD

**Issue by ameihm0912** [mozilla-services/hindsight#169]
Remove CircleCI job from hindsight repo.

@trink do you think it makes sense here to adopt an approach for testing similar to what we have in lua_sandbox_extensions now, but just focused on hindsight itself? The intent would be to move away from duplicated effort building extensions.

Do we get any immediate benefit from building on the various other distributions right now, or can we simplify this?

**Comment by trink** [comment]
We can simplify it.  

Most of the tests for Hindsight exist in the sandbox extensions as integration tests so this setup can just be a verification of the Hindsight build itself with the few unit tests as it requires zero module support.
