### ISSUE TITLE
What is the "production" version of hindsight ?

### ISSUE THREAD

**Issue by Skunnyk** [mozilla-services/hindsight#184]
Hi,

I plan to upgrade my production from hindsight 0.14 to 0.15.
The last available release is 0.15.0 on https://github.com/mozilla-services/hindsight/releases, but in the documentation and in the CMakeLists.txt file, the version is 0.15.3.
Is it a mistake ? What 0.15 version should I use for a production environment ? Can you create a 0.15.3 release ? :)
Thank you for your work !

**Comment by trink** [comment]
Yeah 0.15.3 (master is what we run in production).  I added a tag to make this clearer.
