### ISSUE TITLE
Create a CLI plugin tester

### ISSUE THREAD

**Issue by trink** [mozilla-services/hindsight#19]
Here are some initial thoughts
### heka-cat like behaviour
- #18 e.g., `hindsight_cli  -t output -p debug.lua -i 0.log`
### chaining plugins to test/debug a data flow or run a report
- `hindsight_cli -t analysis -p a.lua -m "Type == 'foo'" -i 0.log |  hindsight_cli -t output -p debug.lua -m "Type == 'a'"`
### cli options
- -t = plugin type (input | analysis | output)
- -p = plugin source
  #### cli options for analysis and output plugins only
  - -i  = input file (defaults to stdin)
  - -m = message matcher (defaults to "TRUE")
  - -ti = ticker interval (defaults to 0)
### general setup
- sandbox limits will be set to unlimited 
- module paths will be picked up through the Lua environment variables
- time will be driven by the data stream.  If you run a days worth of data through in 90 seconds (and ti = 60 then the timer_event will fire 1440 times in that 90 seconds)
- summary stats: performance, memory, instruction, and output limits will be written to stderr
- input and analysis output goes to stdout

**Comment by bbinet** [comment]
it looks great!

**Comment by trink** [comment]
hindsight_cli will remain since it is used for all of our reporting/data playback needs

**Comment by bbinet** [comment]
Ok, so it would be great if it could be documented (see #16)

**Comment by trink** [comment]
Closed in https://github.com/mozilla-services/hindsight/pull/104

hindsight_cli is used for all testing
