### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by hanego** [mozilla-services/hindsight#192]
In the source file src/hs_checkpoint_writer.c, line 167, there is 
`int emps = ...`
When tt << amps, the result is 0 causing the program to have an arithmetic exception.

**Comment by trink** [comment]
There is a check on line 166 testing that amps is not zero https://github.com/mozilla-services/hindsight/blob/master/src/hs_checkpoint_writer.c#L166.  So it should not be happening there.  Do you have a test case that reproduces the FPE?

**Comment by hanego** [comment]
amps is not 0 in my case.
tt = 399, amps = 49873
Then the division of the 2 is 0.
Do you need other files? (My test case is based on confidential infos so I cannot send you directly the configuration or the logs)

**Comment by trink** [comment]
Sorry mis-read the initial comment, thanks.  I will get a PR in shortly.

**Comment by trink** [comment]
https://github.com/mozilla-services/hindsight/pull/193
