### ISSUE TITLE
Clear steps for setting up hindsight

### ISSUE THREAD

**Issue by cweaver1321** [mozilla-services/hindsight#42]
I have read the documentation provided here and on lua_sandbox(_extensions). My documentation-fu is failing to help me find clear steps on setting up dependencies and how to install hindsight properly. 
I have built: 
lua_sandbox
hindsight
librdkafka

I have attempted to build lua_sandbox_extensions but it fails due to not having GEOIP_LIBRARY defined. Is there an easy way to build the individual packages without building everything? Also are there any plans to add documentation on how to install and run hindsight?

Thank you in advance for your time

**Comment by trink** [comment]
In just about all cases you don't want to build everything.  I will look into adding a reasonable default (like build everything with no external dependencies) as for building individual packages yes that is possible.
`cmake -DCMAKE_BUILD_TYPE=release -DEXT_lpeg=on  -DEXT_struct=on ..` (as the examples show (clear your cmake cache first if you already provided different options). During the cmake generation phase you should see the packages available and their status.  If you want  most of the packages it is easier to do something like this `cmake -DCMAKE_BUILD_TYPE=release -DENABLE_ALL_EXT=on -DEXT_geoip=off ..` 

If you already enabled all you can just run`cmake -DEXT_geoip=off ..`

I have been working on the reference docs which are now reasonably complete so the getting started and tutorials will be up next (user contributions are also welcomed).

**Comment by cweaver1321** [comment]
Thank you for the quick response. I did get it to build by enabling only the plugins that I required. It took a lot of fumbling but I figured it out. Are there example configs like there were with heka for setting up any flows through hindsight? Your help is greatly appreciated.

**Comment by cweaver1321** [comment]
Thank you for the quick response

**Comment by trink** [comment]
https://github.com/Securing-DevOps/logging-pipeline
