### ISSUE TITLE
Split out checkpoint removal options 

### ISSUE THREAD

**Issue by trink** [mozilla-services/hindsight#47]
Feedback from Ops: the single setting confusing and they would at least like global configuration options at this granularity:

checkpoint_remove_on_stop = true -- default
checkpoint_remove_on_terminate = false -- default
checkpoint_remove_unused_on_startup = true -- default

see: https://github.com/trink/hindsight/pull/29

**Comment by trink** [comment]
Working on the admin UI dynamic plugin loading has helped clarify the use cases
for checkpoint pruning.

## Conclusion
There should be a single configuration option for output plugins only and it
should be available per plugin.  i.e. a failed mission critical output should be
able to prevent data from being pruned but a failed debug output can just be
ignored.
```lua
output_defaults = {
  remove_checkpoints_on_terminate = false --default
}
```

## Checkpoint Pruning Summary
- To date there is no use case for keeping unused/orphaned checkpoints so they
  should always be deleted and no config option is necessary.
- To date there is no use case fer keeping checkpoints for manually stopped
  output plugins so they should always be deleted (input plugin checkpoints will
  be preserved since the plugin is managing it) and no config option is necessary.
- Checkpoint management for output plugin termination is the only option that
  needs to be exposed to the user.

## Analysis Plugins
- The checkpoint is maintained for the analysis thread and not the individual
  plugin so the stop/terminate scenarios don't apply.

## Input Plugins 
- deleted  - remove
- stop - always preserve
  - shutdown
  - manual restart
  - manual stop
- termination - always preserve
  - failure
  - clean exit
   
## Output Plugins
- deleted = remove
- stop
  - shutdown - always preserve
  - manual restart - always preserve
  - manual stop - always remove,  so pruning will not stop
- termination - user configurable but defaults to preserve (if pruning, it will
  be blocked until the plugin is corrected and can resume where it left off)

@whd @bbinet feedback?

**Comment by bbinet** [comment]
@trink That's perfect for my use cases!

We should also make sure that if Hindsight fails to create an output plugin for any reason, it falls in the "termination" case where its checkpoint removal is managed by `remove_checkpoints_on_terminate`.

Also I think that when we configure an output plugin with `remove_checkpoints_on_terminate=true`, it would also make sense to be able to force the checkpoint reader to starts reading from the most current data (not caring of the old data): see my old PR #30 
What do you think?

**Comment by trink** [comment]
Yeah, I am already looking into PR 30... proposal and branch coming soon but 'current location' will be what you get for all dynamic plugins with no existing checkpoint
