### ISSUE TITLE
hindsight is doing too much disk noise ;-)

### ISSUE THREAD

**Issue by sathieu** [mozilla-services/hindsight#56]
Every second, hindsight is creating hindsight.tsv.tmp, filling it, then moving it to hindsight.cp.

If nothing change, this do unnecessary disk writes. This consumes resources and energy.

Maybe keep the previous cp in memory and rename only if changed?

**Comment by trink** [comment]
hindsight.tsv is every 6 seconds
hindsight.cp is every second.  The resources this operation consumes are pretty minimal and if the checkpoint file is changing then you want to capture that information to persistent storage to minimize the amount of data reprocessed if the system fatally fails or is killed.  A dirty flag could be added but optimizing for a system that processes less than 1 message a second is pretty low priority unless it is adversely effecting the system; However, this would also mean the non idle Hindsight check pointing adversely effects the system, is this the case?

**Comment by sathieu** [comment]
OK. Having the checkpoint updated even without any message in flight (i.e nothing to recover after crash) looks a bit too much. But I don't see a solution given how hindsight works (every message being written to a file anyway).

Also, maybe the tsv interval should be configurable? as this is just for diagnostic.

Closing.
