### ISSUE TITLE
hindsight output try to open "output/analysis/1.log" on every process_message

### ISSUE THREAD

**Issue by champtar** [mozilla-services/hindsight#67]
Hi,

I haven't investigated further, but it seems the output sandbox is trying to open "output/analysis/1.log" on every `process_message()`

a minimal reproduction config (cd in an empty dir and copy in your shell)
```
mkdir -p run/analysis
mkdir -p run/input
mkdir -p run/output

cat > hindsight.cfg <<'EOF'
output_path             = "output"
output_size             = 1024 * 1024 * 1024
sandbox_load_path       = nil -- disable dynamic loading
sandbox_run_path        = "run"
-- sandbox_install_path    = "/usr/share/luasandbox/sandboxes/heka" -- default

analysis_threads        = 1
analysis_lua_path       = "/usr/lib/luasandbox/modules/?.lua"
analysis_lua_cpath      = "/usr/lib/luasandbox/modules/?.so"
--io_lua_path             = analysis_lua_path ..  ";/usr/lib/luasandbox/io_modules/?.lua"
io_lua_path             = analysis_lua_path ..  ";/usr/lib/luasandbox/io_modules/?.lua"
io_lua_cpath            = analysis_lua_cpath .. ";/usr/lib/luasandbox/io_modules/?.so"

analysis_defaults = {}
input_defaults = {}
output_defaults = {}
EOF

cat > run/input/input_test.lua <<'EOF'
local msg = {
Timestamp   = nil,
Type        = "access-logs",
Hostname    = "aaaa",
Logger      = "FileTest",
Payload     = nil,
Fields      = nil
}

function process_message(offset)
    while true do
        inject_message(msg)
    end
end
EOF

cat > run/input/input_test.cfg <<'EOF' 
filename = "input_test.lua"
instruction_limit = 0
EOF

cat > run/output/counter.lua <<'EOF'
local cnt = 0

function process_message()
    cnt = cnt + 1
    return 0
end

function timer_event()
    print(cnt)
end
EOF

cat > run/output/counter.cfg <<'EOF'
filename 	= "counter.lua"
message_matcher = "TRUE"
ticker_interval = 10
EOF
```

strace -e trace=open -f hindsight_cli hindsight.cfg 7

Thanks for hindsight!

**Comment by trink** [comment]
It should be once a second, it is polling for new data

**Comment by trink** [comment]
This is correct behavior as it is is trying to demux the input/analysis streams before processing.  If the analysis plugins were actually outputting data it would simply be a read but in this case it is waiting for the next file to appear.

**Comment by champtar** [comment]
ok thanks

**Comment by trink** [comment]
But yeah looking at the code this could be improved... reopening as an enhancement

**Comment by trink** [comment]
@champtar This branch has a patch https://github.com/mozilla-services/hindsight/tree/reduce_polling_opens

**Comment by champtar** [comment]
Thanks @trink
Will try it tommorow

**Comment by champtar** [comment]
this works for me, not much performance changes, but this works

**Comment by trink** [comment]
Yeah, performance wise it wasn't really an issues but this is cleaner so thank you for the feedback.

https://github.com/mozilla-services/hindsight/pull/68
