### ISSUE TITLE
hindsight anaysis thread stuck because of missing input log file

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/hindsight#76]
I noticed that the analysis thread of my Hindsight server was stuck today, and it won't read the input log files anymore.
Finally I discovered that an input log files was missing: Hindsight was stuck because it was trying to open a new log file for reading but for some obscure reason, the log file didn't exist...
So a temporary fix was simply to `touch /var/lib/hindsight/input/1745.log` to create an empty file, and Hindsight analysis thread was automatically unlocked and continued its work.

I have no idea why the `/var/lib/hindsight/input/1745.log` input log file was missing since `/var/lib/hindsight/input/1744.log` and `/var/lib/hindsight/input/1746.log` log files were both available, and nobody has access to this server.

Any idea?

**Comment by bbinet** [comment]
Also note that the build of hindsight I'm using is a little bit out of date, here is the last commit of my build: 9593668

**Comment by trink** [comment]
Any errors in the log? If not it has to be a sequencing error which I have never seen (we produce thousands of queue files per day) or a prune error which we have also never seen.  There have been code changes in this area since the release you are using but nothing really relevant.

**Comment by bbinet** [comment]
No error in the log.
It is also the first time I see such a case myself.

**Comment by bbinet** [comment]
But I have many warning of this kind:

```
1484756232030283198 [warning] lsb_decode_heka_message tag:0 wiretype:1 position:40
1484756238706990118 [warning] lsb_decode_heka_message tag:29 wiretype:2 position:605
1484756238720592525 [warning] lsb_decode_heka_message tag:15 wiretype:7 position:221
1484756238734893345 [warning] lsb_decode_heka_message tag:29 wiretype:2 position:605
1484756247531016096 [warning] lsb_decode_heka_message tag:10 wiretype:2 position:199
1484756283238895066 [warning] lsb_decode_heka_message tag:26 wiretype:1 position:198
1484756830815059045 [warning] lsb_decode_heka_message tag:10 wiretype:2 position:198
1484757139747502265 [warning] lsb_decode_heka_message tag:3 wiretype:3 position:290
1484757175170986424 [warning] lsb_decode_heka_message tag:7 wiretype:4 position:290
```

**Comment by trink** [comment]
That is a different problem. The only time this should occur in the internal queue is if the process is terminated (there is also a case where a mis-configured output_limit/max_message_size could cause messages to be skipped and those errors can be generated during the seek)

**Comment by methodmissing** [comment]
We've had some similar issues once, but tracked it down to a parity mismatch between the `threads` config value and actual running analysis threads. Our observations and conclusions was that the analysis thread tracks some critical bits that determine if backpressure should be applied and it shouldn't apply backpressure if the thread is orphaned (not running an analysis plugin)

PR inbound soon.

**Comment by trink** [comment]
We have been monitoring this for the last year with no re-occurrence so I am closing it out.
