### ISSUE TITLE
Allow output plugins to subscribe to a particular queue

### ISSUE THREAD

**Issue by trink** [mozilla-services/hindsight#93]
read_queue = "(input|analysis|both)"  -- default to both, the current behavior

**Comment by champtar** [comment]
Hi @trink,
do you expect any performance boost, or it's to "improve"/"extend" message_matcher

**Comment by trink** [comment]
It is mainly for things like our alert and inject payload outputs, there is no reason to have them reading an extra 800MM input messages a day that will never match.

**Comment by bbinet** [comment]
Cool, it would also be very useful for me!

**Comment by trink** [comment]
Closed by 8fd0b676bec60d131a370582875c785b9cbf6f29
